
name: 自动打包斐讯 N1 专属固件

on:
  workflow_dispatch: # 允许手动点击按钮触发打包

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 结账代码
      uses: actions/checkout@v4

    - name: 核心打包步骤
      uses: ophub/flippy-openwrt-actions@main
      env:
        # [100%真实有效直链] 官方标准 ARMv8 基础 rootfs 包，完美内置 PassWall
        OPENWRT_ARMSR: https://github.com/ophub/flippy-openwrt-actions/releases/download/OpenWrt_armv8_save_2026.06/openwrt-armsr-armv8-generic-rootfs.tar.gz
        
        # [精准定制] 仅打包斐讯 N1 对应的晶晨芯片架构
        PACKAGE_SOC: s905d
        
        # [精准定制] 强行指定打包出来的固件默认后台 IP 为 192.168.2.8
        OPENWRT_IP: 192.168.2.8
        
        # 使用 Flippy 推荐的最稳定的 6.12.y 内核系列
        KERNEL_VERSION_NAME: 6.12.y
        KERNEL_AUTO_LATEST: true
        GZIP_IMGS: .img.gz

    - name: 上传打包好的 N1 固件到 GitHub Release
      uses: softprops/action-gh-release@v2
      if: env.PACKAGED_STATUS == 'success'
      with:
        tag_name: N1-OpenWrt-${{ env.PACKAGED_OUTPUTDATE }}
        files: ${{ env.PACKAGED_OUTPUTPATH }}/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
